name = "workertest"
main = "src/worker.ts"
compatibility_date = "2023-11-21"
compatibility_flags = [ "nodejs_compat" ]

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"
preview_bucket_name = "my-bucket-preview"
