name = "workerqueuetest"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[queues.consumers]]
queue = "workerqueuetest"

[[queues.producers]]
queue = "workerqueuetest"
binding = "WORKERTEST_QUEUE"

