name = "app"
main = "src/index.ts"
compatibility_date = "2023-01-29"


# Disable *.workers.dev
# see https://developers.cloudflare.com/workers/wrangler/configuration
workers_dev = false

[triggers]
crons = [ ]