name = "tailworker"
main = "src/worker.ts"
compatibility_date = "2023-11-08"

tail_consumers = [
    {service = "slackworker"},
    {service = "cf-tail-logger"}
]

kv_namespaces = [
    { binding = "TAIL_SAMPLE", id = "89dce8397e7e4dcbaa71810befba3cd5" }
]

[[queues.producers]]
queue = "slackqueue"
binding = "SQUEUE"
