version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/gateway"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
